Add snapshot pull command
wposs/snapshot-command pull request #16
Opened 2020-09-19 12:27 UTC by abhijitrakas

2020-09-19 12:27 UTC, abhijitrakas commented
@thrijith Please review this PR when you get time.

2020-09-19 13:00 UTC, thrijith requested changes
Minor query/changes.

2020-09-19 15:35 UTC, thrijith approved these changes

2020-09-19 15:35 UTC, thrijith commented on src/SnapshotCommand.php
> +		$zip_content   = $this->get_zip_contents( $snapshot_name ); // Get all the backup zip content.
```suggestion
		$zip_content = $this->get_zip_contents( $snapshot_name ); // Get all the backup zip content.
```

2020-09-19 15:35 UTC, thrijith commented on src/SnapshotStorage.php
> +		} catch ( S3Exception $e ) {
```suggestion
		} catch ( \S3Exception $e ) {
```

2020-09-20 04:52 UTC, abhijitrakas commented
@thrijith - Please review it again. But don't merge.

2020-09-20 07:12 UTC, thrijith approved these changes

2020-09-20 07:12 UTC, merged